### ISSUE TITLE
Unable to Fetch From Google Drive anymore.

### ISSUE THREAD

**Issue by vkazheng** [ssnjrthegr8/stremio-gdrive#35]
```
2023-02-02T03:24:47.770 app[e7885b13] sin [info] [2023-02-02 03:24:47 +0000] [528] [ERROR] Error handling request

2023-02-02T03:24:47.770 app[e7885b13] sin [info] Traceback (most recent call last):

2023-02-02T03:24:47.770 app[e7885b13] sin [info] File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 184, in handle_request

2023-02-02T03:24:47.770 app[e7885b13] sin [info] for item in respiter:

2023-02-02T03:24:47.770 app[e7885b13] sin [info] File "/app/.heroku/python/lib/python3.9/site-packages/werkzeug/wsgi.py", line 462, in __next__

2023-02-02T03:24:47.770 app[e7885b13] sin [info] return self._next()

2023-02-02T03:24:47.770 app[e7885b13] sin [info] File "/app/.heroku/python/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 49, in _iter_encoded

2023-02-02T03:24:47.770 app[e7885b13] sin [info] for item in iterable:

2023-02-02T03:24:47.770 app[e7885b13] sin [info] File "/app/sgd/routes.py", line 63, in get_streams

2023-02-02T03:24:47.770 app[e7885b13] sin [info] stream_meta = Meta(stream_type, stream_id)

2023-02-02T03:24:47.770 app[e7885b13] sin [info] File "/app/sgd/meta.py", line 120, in __init__

2023-02-02T03:24:47.770 app[e7885b13] sin [info] IMDb.__init__(self)

2023-02-02T03:24:47.770 app[e7885b13] sin [info] File "/app/sgd/meta.py", line 21, in __init__

2023-02-02T03:24:47.770 app[e7885b13] sin [info] if not self.get_meta_from_imdb_sg():

2023-02-02T03:24:47.770 app[e7885b13] sin [info] File "/app/sgd/meta.py", line 85, in get_meta_from_imdb_sg

2023-02-02T03:24:47.770 app[e7885b13] sin [info] self.set_meta(meta[0], year="y", name="l")

2023-02-02T03:24:47.770 app[e7885b13] sin [info] TypeError: set_meta() got an unexpected keyword argument 'name'

```

Not a programmer, need help when you have time please.

**Comment by vkazheng** [comment]
changing `self.set_meta(meta[0], year="y", name="l"` to  `self.set_meta(meta[0], year="y", title="l"` solves it

**Comment by zDuts** [comment]
> changing `self.set_meta(meta[0], year="y", name="l"` to `self.set_meta(meta[0], year="y", title="l"` solves it

Thanks it works for some but not all.
E.g. The Last of Us works, but not Severance.
Severance get read as "Central Awards" in name.
Any idea?

**Comment by vkazheng** [comment]
> > changing `self.set_meta(meta[0], year="y", name="l"` to `self.set_meta(meta[0], year="y", title="l"` solves it
> 
> Thanks it works for some but not all. E.g. The Last of Us works, but not Severance. Severance get read as "Central Awards" in name. Any idea?

Yes, this is what i noticed too, i am not sure for now, need to google more as i dont code

**Comment by vkazheng** [comment]
and fetching everything everywhere all at once returning "awards central" as well
and it is somehow fetching from cache instead of the IMDB

`Reading /tmp/tt6710474.json!
Fetched metadata for tt6710474 from CACHE:
Titles (1) -> ['awards central']
Year: 
Saving /tmp/drivenames.json!
Got 0/0 unique results from gdrive after deduping in 0.282s. Processing results...
Fetched access_token, will expire at 2023-02-08 11:02:04.818648
Fetched 0/0 valid stream(s) in 0.282s for tt6710474 -> ["name contains 'awards' and name contains 'central' and name contains ''"]`

**Comment by zDuts** [comment]
> and fetching everything everywhere all at once returning "awards central" as well and it is somehow fetching from cache instead of the IMDB
> 
> `Reading /tmp/tt6710474.json! Fetched metadata for tt6710474 from CACHE: Titles (1) -> ['awards central'] Year: Saving /tmp/drivenames.json! Got 0/0 unique results from gdrive after deduping in 0.282s. Processing results... Fetched access_token, will expire at 2023-02-08 11:02:04.818648 Fetched 0/0 valid stream(s) in 0.282s for tt6710474 -> ["name contains 'awards' and name contains 'central' and name contains ''"]`

Fixed it, comment out line 20 and line 21 (just add a # in front).
That way you don't use the suggestion thing from imdb. 
It uses CINEMETA instead to search for the title.
I feel like it's faster too.

After the oscars it's probably fine to put it back in.
The issue is that now you get awards central first when searching for the imdb reference tt-number.
You can see it as well on imdb's website if you search for "Severance" or "Everything Everywhere All At Once" the first thing in the dropdown will be "Awards Central" and second will be the actual series or movie.
It's probably better to just put the whole imdb_sg thing a the end so you can still use it as a fallback but i don't know how to code either 🗡️ 
e.g. https://v2.sg.media-imdb.com/suggests/t/tt6710474.json

        #    self.fetch_dest = "IMDB_SG_API"
         #   if not self.get_meta_from_imdb_sg():
